name: ECS application deployment

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter the branch name'
        required: true
        default: 'paramesh-dev'
        type: string

env:
  IMAGE_REPO_NAME: "github-action-cicd"
  IMAGE_TAG: "latest"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.name }}
      
      - name: Checking context variable
        run: |
          echo "Repository name: ${{ github.repository }}"
          echo "Workflow name: ${{ github.workflow }}"
          echo "Triggered by: ${{ github.triggering_actor }}"

  ecr-push:
    runs-on: self-hosted
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Assume OIDC role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: githuboidctest
      
      - name: Get Parameters from SSM
        run: |
          echo "IMAGE_REPO_NAME=$(aws ssm get-parameter --name "/GithubAction/demo/Reponame/Ecrname" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(aws ssm get-parameter --name "/GithubAction/demo/Tag/Imagetag" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=$(aws ssm get-parameter --name "/GithubAction/demo/Account/Accountid" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "AWS_REGION=$(aws ssm get-parameter --name "/GithubAction/demo/Region/Awsregion" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "ECS_CLUSTER=$(aws ssm get-parameter --name "/GithubAction/demo/Reponame/Ecscluster" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "ECS_SERVICE=$(aws ssm get-parameter --name "/GithubAction/demo/Servicename/Ecsservice" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
      
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
      
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }}

  ecs-deploy:
    runs-on: self-hosted
    needs: ecr-push
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Assume OIDC role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: githuboidctest
          
      - name: Debug Variables
        run: |
          echo "Using ECS_CLUSTER: ${{ env.ECS_CLUSTER }}"
          echo "Using ECS_SERVICE: ${{ env.ECS_SERVICE }}"
          if [[ -z "${{ env.ECS_CLUSTER }}" || -z "${{ env.ECS_SERVICE }}" ]]; then
            echo "Error: Missing required environment variables!"
            exit 1
          fi
      
      - name: Deployment to ECS
        run: |
          desired_task_count=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query 'services[*].desiredCount' --output text)
          echo "Desired task count: $desired_task_count"
          
          task_arns=$(aws ecs list-tasks --cluster ${{ env.ECS_CLUSTER }} --service-name ${{ env.ECS_SERVICE }} --query 'taskArns[*]' --output text)
          if [ -n "$task_arns" ]; then
            echo "Stopping running tasks..."
            for task in $task_arns; do
              aws ecs stop-task --cluster ${{ env.ECS_CLUSTER }} --task $task
            done
          else
            echo "No tasks are currently running."
          fi
          
          echo "Restoring desired count to $desired_task_count"
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --desired-count $desired_task_count
