name: OIDC testing

on:
  push
env:
  AWS_REGION : "us-east-1"
jobs:
  oidc:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assume OIDC role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::976193224554:role/github-action-oidc
          role-session-name: githuboidctest
