name: Manual Trigger Input Branch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch to run the workflow on'
        required: true
        default: 'paramesh-dev'
env:
  AWS_REGION: "us-east-1"
  
jobs:
  run_on_target_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Display selected branch
        run: echo "Running on branch ${{ github.event.inputs.target_branch }}"
      
      - name: Assume OIDC role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: githuboidctest

      - name: Checking context variable
        run: |
          echo "Current Branch: ${{ github.ref }}"
          echo "Repository name: ${{ github.repository }}"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) 
