name: Multi-Branch Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - paramesh-dev
env:
  AWS_REGION: "us-east-1"

jobs:
  checkout:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Assume OIDC role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: githuboidctest
  s3-push:
    runs-on: ubuntu-latest
    needs: checkout
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Create File and Add Content
        run: |
          echo "This is a test file created by GitHub Actions." > test.txt
          echo "Timestamp: $(date)" >> test.txt
          cat test.txt
      
      - name: Assume OIDC role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: githuboidctest
      
      - name: Upload File to S3
        run: |
          aws s3 cp test.txt s3://devops-artifact-bkt/test.txt

      - name: Deploy Based on Branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying to Production..."
            # Add production deployment commands here
          elif [[ "${{ github.ref }}" == "refs/heads/paramesh-dev" ]]; then
            echo "Deploying to Staging..."
            # Add dev deployment commands here
          else
            echo "No deployment for this branch."
        shell: bash
