name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  S3BUCKET: devops-artifact-bkt

jobs:
  test:
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read
    runs-on: [self-hosted, runner-1]  # Ensure this runner is registered
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION_NAME }}
          
      - name: Create a directory
        run: mkdir -p /home/ubuntu/dhruva

  deploy:
    needs: test  # Ensures 'deploy' runs only after 'test' succeeds
    permissions:
      id-token: write
      contents: read
    runs-on: [self-hosted, runner-2]  # Ensure 'runner-2' exists and is online
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Create a directory
        run: mkdir -p /home/ubuntu/dhruva
